version: '3.8'

services:
  web:
    image: odoo:17.0 
    depends_on:
      - db
    ports:
      - "8069:8069" 
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo 
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo 
      - POSTGRES_USER=odoo
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  odoo_data:
  db_data:
