version: '3.8'

services:
  web:
    image: odoo:17.0 # Puedes cambiar la versión de Odoo aquí (ej: odoo:16.0)
    depends_on:
      - db
    ports:
      - "8069:8069" # Puerto de Odoo: HOST:CONTAINER
    volumes:
      - odoo_data:/var/lib/odoo # Volumen para datos de Odoo
      - ./config:/etc/odoo # Carpeta para el archivo de configuración de Odoo
      - ./custom_addons:/mnt/extra-addons # Carpeta para tus módulos personalizados
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15 # Versión de PostgreSQL
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo # Contraseña de la base de datos (¡cambia esto en producción!)
      - POSTGRES_USER=odoo # Usuario de la base de datos
    volumes:
      - db_data:/var/lib/postgresql/data # Volumen para los datos de la base de datos

volumes:
  odoo_data:
  db_data:
